<?php

namespace Database\Seeders;

use App\Models\StudyTopic;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Guia ENEM — temas EDITORIAIS (roteiro de estudo), organizados por eixo e disciplina,
 * com o detalhamento do que estudar em cada um. Recorrência (1–3) é uma indicação
 * pedagógica editorial; a contagem de questões oficiais vem das classificações VERIFIED.
 * Nada aqui é apresentado como questão ou conteúdo oficial do Inep.
 */
class StudyTopicsSeeder extends Seeder
{
    /** @return array<int, array{0:string,1:string,2:string,3:string,4:array<int,string>,5:int,6?:string}> [area, disciplina, nome, descrição, subtemas, recorrência, habilidade] */
    public static function topics(): array
    {
        return [
            // ------------------------------------------------------------------ LINGUAGENS
            ['LINGUAGENS', 'Português', 'Interpretação de texto', 'A base de toda a prova de Linguagens: identificar tese, argumentos, ironia, pressupostos e a intenção do autor em textos de gêneros variados.', ['Ideia central x ideias secundárias', 'Inferência e pressupostos', 'Ironia, humor e ambiguidade', 'Relação título–texto', 'Intertextualidade e paráfrase', 'Leitura de charges, tirinhas e infográficos'], 3, 'H1'],
            ['LINGUAGENS', 'Português', 'Gêneros textuais', 'Reconhecer a estrutura, a finalidade e o suporte de cada gênero (notícia, editorial, crônica, anúncio, resenha, carta, meme, verbete).', ['Gêneros jornalísticos: notícia, reportagem, editorial, artigo de opinião', 'Gêneros publicitários e persuasão', 'Gêneros digitais: post, meme, thread, podcast', 'Gêneros instrucionais e normativos', 'Sequências tipológicas: narrar, descrever, argumentar, expor, injuntivo'], 3, 'H2'],
            ['LINGUAGENS', 'Português', 'Funções da linguagem', 'As seis funções de Jakobson e como identificá-las pela ênfase em cada elemento da comunicação.', ['Referencial, emotiva, conativa', 'Metalinguística, fática, poética', 'Elementos da comunicação (emissor, receptor, canal, código, mensagem, referente)', 'Função predominante em anúncios e poemas'], 3, 'H2'],
            ['LINGUAGENS', 'Português', 'Variação linguística e preconceito linguístico', 'Variedades regionais, sociais, históricas e situacionais; norma-padrão x uso; adequação ao contexto.', ['Variação diatópica, diastrática, diafásica e diacrônica', 'Norma-padrão, norma culta e variedades populares', 'Preconceito linguístico (Marcos Bagno)', 'Oralidade x escrita', 'Gírias, jargões e regionalismos em textos'], 3, 'H3'],
            ['LINGUAGENS', 'Português', 'Figuras de linguagem', 'Recursos expressivos que ampliam ou desviam o sentido literal, muito cobrados em poemas, anúncios e canções.', ['Metáfora, metonímia, comparação, catacrese', 'Hipérbole, eufemismo, ironia, antítese, paradoxo', 'Personificação (prosopopeia), sinestesia', 'Aliteração, assonância, onomatopeia', 'Efeito de sentido no contexto'], 2, 'H1'],
            ['LINGUAGENS', 'Português', 'Coesão e coerência', 'Mecanismos que articulam as partes do texto: conectivos, referenciação, progressão temática.', ['Conectivos e relações lógicas (causa, oposição, conclusão, condição)', 'Anáfora, catáfora, elipse', 'Substituição lexical e pronominal', 'Coerência: não contradição, progressão, articulação', 'Uso na redação (competência 4)'], 3, 'H4'],
            ['LINGUAGENS', 'Português', 'Semântica: sentido das palavras', 'Sinonímia, antonímia, polissemia, ambiguidade, denotação e conotação — e o efeito de cada escolha lexical.', ['Denotação x conotação', 'Polissemia e homonímia', 'Ambiguidade intencional em anúncios e humor', 'Campo semântico e seleção lexical', 'Neologismos e estrangeirismos'], 2, 'H1'],
            ['LINGUAGENS', 'Português', 'Sintaxe e concordância', 'Estrutura da oração e do período; concordância verbal e nominal, regência e crase na norma-padrão.', ['Sujeito, predicado, complementos e adjuntos', 'Período composto: coordenação e subordinação', 'Concordância verbal e nominal', 'Regência e crase', 'Colocação pronominal', 'Pontuação e efeito de sentido'], 2, 'H4'],
            ['LINGUAGENS', 'Português', 'Argumentação e persuasão', 'Estratégias argumentativas em textos de opinião e publicitários: tipos de argumento, falácias e recursos retóricos.', ['Argumento de autoridade, exemplificação, causa e consequência, comparação', 'Falácias comuns', 'Modalizadores e marcas de subjetividade', 'Estratégias publicitárias (apelo emocional, imperativo, slogan)', 'Contra-argumentação'], 2, 'H2'],
            ['LINGUAGENS', 'Literatura', 'Escolas literárias: Barroco ao Romantismo', 'Características, contexto e autores do Quinhentismo, Barroco, Arcadismo e Romantismo no Brasil.', ['Literatura de informação e jesuítica', 'Barroco: Gregório de Matos, Padre Vieira', 'Arcadismo: Cláudio Manuel da Costa, Tomás Antônio Gonzaga', 'Romantismo: gerações indianista, ultrarromântica e condoreira', 'Prosa romântica: José de Alencar, Manuel Antônio de Almeida'], 2, 'H5'],
            ['LINGUAGENS', 'Literatura', 'Realismo, Naturalismo e Parnasianismo', 'A crítica social do século XIX: Machado de Assis, Aluísio Azevedo e a poesia parnasiana.', ['Machado de Assis: narrador, ironia e Memórias Póstumas', 'Naturalismo: O Cortiço e determinismo', 'Parnasianismo: forma, Olavo Bilac', 'Simbolismo: Cruz e Sousa, Alphonsus de Guimaraens', 'Contexto: abolição, República e ciência'], 2, 'H5'],
            ['LINGUAGENS', 'Literatura', 'Modernismo brasileiro', 'Semana de 22, as três fases modernistas e a poesia e prosa que mais aparecem no ENEM.', ['Pré-modernismo: Lima Barreto, Euclides da Cunha, Monteiro Lobato', 'Semana de Arte Moderna e manifestos (Pau-Brasil, Antropofágico)', '1ª fase: Mário e Oswald de Andrade, Manuel Bandeira', '2ª fase: Drummond, Cecília Meireles, Vinicius; romance de 30 (Graciliano, Rachel de Queiroz, Jorge Amado)', '3ª fase: Clarice Lispector, Guimarães Rosa, João Cabral'], 3, 'H5'],
            ['LINGUAGENS', 'Literatura', 'Literatura contemporânea e africana de língua portuguesa', 'Autores pós-1960, poesia marginal, literatura periférica, indígena e afro-brasileira; autores africanos lusófonos.', ['Concretismo e poesia marginal', 'Literatura periférica: Carolina Maria de Jesus, Ferréz, Conceição Evaristo', 'Literatura indígena: Daniel Munduruku, Ailton Krenak', 'Mia Couto, Pepetela, José Eduardo Agualusa', 'Crônica contemporânea: Luis Fernando Verissimo, Rubem Braga'], 2, 'H5'],
            ['LINGUAGENS', 'Literatura', 'Gêneros literários e versificação', 'Épico, lírico e dramático; métrica, rima, ritmo e figuras de som.', ['Gêneros lírico, épico e dramático', 'Verso, estrofe, métrica e rima', 'Soneto, haicai, verso livre', 'Narrador, foco narrativo, tempo e espaço', 'Teatro: Nelson Rodrigues, Ariano Suassuna, Gil Vicente'], 2, 'H5'],
            ['LINGUAGENS', 'Artes', 'Arte e movimentos artísticos', 'Leitura de obras e movimentos: do Renascimento às vanguardas e à arte contemporânea brasileira.', ['Renascimento, Barroco e Neoclassicismo', 'Vanguardas europeias: cubismo, expressionismo, surrealismo, dadaísmo', 'Modernismo brasileiro: Tarsila, Anita Malfatti, Portinari', 'Arte contemporânea: instalação, performance, grafite', 'Patrimônio cultural material e imaterial'], 2, 'H4'],
            ['LINGUAGENS', 'Artes', 'Música e cultura popular brasileira', 'Gêneros musicais, Tropicália, MPB, samba, funk e rap como manifestações culturais e políticas.', ['Samba, choro e bossa nova', 'Tropicália e a censura', 'Rap, funk e cultura periférica', 'Música como resistência e identidade', 'Leitura de letras de canção na prova'], 2, 'H3'],
            ['LINGUAGENS', 'Educação Física', 'Corpo, esporte e sociedade', 'Esporte, lazer, saúde e corpo como construção cultural; inclusão e estereótipos.', ['Esporte de rendimento x esporte de lazer', 'Atividade física, saúde e sedentarismo', 'Corpo, padrões estéticos e mídia', 'Jogos, brincadeiras e cultura corporal', 'Inclusão, gênero e esporte paralímpico'], 2, 'H3'],
            ['LINGUAGENS', 'Tecnologias da Informação', 'Comunicação, mídia e redes sociais', 'Impactos das tecnologias digitais na linguagem, na informação e nas relações: fake news, algoritmos, privacidade.', ['Fake news e checagem de fatos', 'Bolhas, algoritmos e viés de confirmação', 'Cultura digital e novos gêneros', 'Privacidade e dados pessoais', 'Publicidade e influenciadores'], 2, 'H1'],
            ['LINGUAGENS', 'Inglês/Espanhol', 'Leitura em língua estrangeira', 'As cinco questões de língua estrangeira cobram compreensão global e inferência — não gramática isolada.', ['Skimming e scanning', 'Cognatos e falsos cognatos', 'Palavras-chave e contexto', 'Gêneros: poema, tirinha, notícia, cartaz, letra de música', 'Expressões idiomáticas frequentes'], 3, 'H5'],
            ['LINGUAGENS', 'Inglês/Espanhol', 'Cultura e identidade em textos estrangeiros', 'Textos que discutem imigração, diversidade, direitos e cultura em países de língua inglesa e espanhola.', ['Imigração e fronteira (EUA–México)', 'Identidade latino-americana', 'Direitos civis e movimentos sociais', 'Variedades do inglês e do espanhol', 'Ironia e crítica social em charges'], 2, 'H6'],
            ['LINGUAGENS', 'Redação', 'Estrutura dissertativo-argumentativa', 'Introdução com tese, dois parágrafos de desenvolvimento e conclusão com proposta de intervenção.', ['Introdução: contextualização + tese + projeto de texto', 'Desenvolvimento: tópico frasal, argumento, repertório, fechamento', 'Conclusão: retomada + proposta de intervenção', 'Distribuição das 30 linhas', 'Evitar cópia dos textos motivadores'], 3, 'C2'],
            ['LINGUAGENS', 'Redação', 'Proposta de intervenção', 'A competência 5 exige agente, ação, meio/modo, finalidade e detalhamento, respeitando os direitos humanos.', ['Os cinco elementos da proposta', 'Agentes possíveis: Estado, escola, mídia, sociedade civil, família', 'Detalhamento e viabilidade', 'Ligação da proposta com os argumentos', 'Respeito aos direitos humanos'], 3, 'C5'],
            ['LINGUAGENS', 'Redação', 'Repertório sociocultural', 'Como usar dados, obras, autores, leis e fatos históricos de forma produtiva e pertinente ao tema.', ['Repertório legitimado x senso comum', 'Filosofia e sociologia úteis (Bauman, Foucault, Hannah Arendt, Djamila Ribeiro)', 'Constituição, ECA, LGPD, Estatuto do Idoso', 'Séries, filmes e livros como repertório', 'Como conectar o repertório ao argumento'], 3, 'C3'],
            ['LINGUAGENS', 'Redação', 'Norma-padrão na redação', 'Erros de língua que mais tiram pontos na competência 1: concordância, crase, vírgula, acentuação e registro.', ['Vírgula entre sujeito e verbo, orações adverbiais', 'Crase e regência', 'Concordância verbal com sujeito posposto', 'Acentuação e ortografia', 'Marcas de oralidade e informalidade'], 2, 'C1'],

            // ------------------------------------------------------------------ HUMANAS
            ['HUMANAS', 'História', 'Brasil Colônia', 'Da colonização portuguesa ao século XVIII: economia açucareira, escravidão, mineração e revoltas.', ['Pacto colonial e capitanias', 'Engenho, açúcar e escravidão africana', 'Povos indígenas e resistência', 'Mineração, Inconfidência Mineira e Conjuração Baiana', 'União Ibérica, invasões holandesas e bandeirantes'], 2, 'H11'],
            ['HUMANAS', 'História', 'Brasil Império', 'Independência, Primeiro Reinado, Regências, Segundo Reinado, abolição e crise do Império.', ['Independência e Constituição de 1824', 'Período regencial e revoltas (Cabanagem, Balaiada, Farroupilha, Sabinada)', 'Café, imigração e Lei de Terras', 'Guerra do Paraguai', 'Abolição gradual: Eusébio de Queirós, Ventre Livre, Sexagenários, Áurea'], 2, 'H12'],
            ['HUMANAS', 'História', 'Brasil República: da Proclamação a 1930', 'República da Espada, política dos governadores, coronelismo, revoltas sociais e a crise de 1930.', ['Proclamação e Constituição de 1891', 'Política do café com leite e coronelismo', 'Canudos, Contestado, Revolta da Vacina, Revolta da Chibata', 'Tenentismo e Semana de 22', 'Revolução de 1930'], 3, 'H13'],
            ['HUMANAS', 'História', 'Era Vargas', 'Governo Provisório, Constitucionalista, Estado Novo, trabalhismo e a construção do Estado moderno.', ['Revolução Constitucionalista de 1932', 'Intentona Comunista e Estado Novo', 'CLT, sindicalismo e populismo', 'DIP, propaganda e censura', 'Segundo governo Vargas e o suicídio'], 3, 'H13'],
            ['HUMANAS', 'História', 'Ditadura militar (1964–1985)', 'Golpe de 1964, atos institucionais, repressão, milagre econômico, resistência e redemocratização.', ['Contexto da Guerra Fria e o golpe', 'AI-5 e anos de chumbo', 'Milagre econômico e endividamento', 'Resistência cultural: Tropicália, Chico, MPB', 'Abertura lenta e gradual, Diretas Já, Constituição de 1988'], 3, 'H14'],
            ['HUMANAS', 'História', 'Brasil redemocratizado', 'Constituição Cidadã, Plano Real, políticas sociais e desafios recentes.', ['Constituição de 1988 e direitos sociais', 'Hiperinflação e Plano Real', 'Impeachments de 1992 e 2016', 'Políticas de inclusão e cotas', 'Movimentos sociais contemporâneos'], 2, 'H14'],
            ['HUMANAS', 'História', 'Antiguidade e Idade Média', 'Grécia, Roma, cristianismo, feudalismo, Igreja e Islã — sempre em diálogo com o presente.', ['Democracia ateniense x democracia moderna', 'República e Império romanos', 'Feudalismo e sociedade estamental', 'Igreja medieval, Cruzadas e Inquisição', 'Expansão islâmica e trocas culturais'], 2, 'H11'],
            ['HUMANAS', 'História', 'Idade Moderna: Renascimento, Reformas e Absolutismo', 'Humanismo, Reforma Protestante, Estado absolutista e Grandes Navegações.', ['Renascimento e antropocentrismo', 'Reforma e Contrarreforma', 'Absolutismo e mercantilismo', 'Grandes Navegações e colonização', 'Iluminismo e crítica ao Antigo Regime'], 2, 'H11'],
            ['HUMANAS', 'História', 'Revoluções burguesas e Revolução Industrial', 'Revolução Inglesa, Americana e Francesa; industrialização e nascimento do movimento operário.', ['Revolução Francesa: fases e legado', 'Independência dos EUA', 'Revolução Industrial: fases, urbanização e trabalho', 'Ludismo, cartismo e sindicatos', 'Liberalismo, socialismo e anarquismo'], 2, 'H12'],
            ['HUMANAS', 'História', 'Imperialismo, Guerras Mundiais e Guerra Fria', 'Neocolonialismo, as duas guerras, totalitarismos, bipolaridade e descolonização.', ['Partilha da África e da Ásia', 'Primeira Guerra e Revolução Russa', 'Nazismo, fascismo e Holocausto', 'Segunda Guerra e ONU', 'Guerra Fria, descolonização e Apartheid'], 3, 'H13'],
            ['HUMANAS', 'História', 'África e cultura afro-brasileira', 'Reinos africanos, tráfico atlântico, resistência escrava, quilombos e legado cultural (Lei 10.639).', ['Reinos do Mali, Congo e Zimbábue', 'Tráfico atlântico e diáspora', 'Quilombos, Palmares e revoltas (Malês)', 'Religiões de matriz africana', 'Racismo estrutural e políticas afirmativas'], 3, 'H14'],
            ['HUMANAS', 'História', 'Povos indígenas no Brasil', 'Diversidade, colonização, legislação e lutas contemporâneas por terra e direitos.', ['Diversidade linguística e cultural', 'Escravidão indígena e missões', 'Constituição de 1988 e demarcação de terras', 'Marco temporal e conflitos atuais', 'Cosmovisões indígenas (Krenak, Kopenawa)'], 2, 'H14'],
            ['HUMANAS', 'Geografia', 'Urbanização e questões urbanas', 'Crescimento das cidades, segregação, mobilidade, moradia e problemas ambientais urbanos.', ['Êxodo rural e metropolização', 'Segregação socioespacial e periferias', 'Mobilidade urbana e transporte', 'Ilhas de calor, enchentes e impermeabilização', 'Estatuto da Cidade e direito à cidade'], 3, 'H17'],
            ['HUMANAS', 'Geografia', 'Meio ambiente e sustentabilidade', 'Desmatamento, mudanças climáticas, matriz energética, conferências e desenvolvimento sustentável.', ['Aquecimento global e efeito estufa', 'Desmatamento da Amazônia e do Cerrado', 'Conferências: Estocolmo, Rio-92, Kyoto, Paris', 'Matriz energética brasileira e transição', 'Consumo, resíduos e economia circular'], 3, 'H18'],
            ['HUMANAS', 'Geografia', 'Globalização e geopolítica', 'Fluxos de capital, blocos econômicos, multipolaridade, conflitos e organismos internacionais.', ['Blocos econômicos: UE, Mercosul, BRICS', 'Divisão internacional do trabalho', 'Conflitos contemporâneos e refugiados', 'Nacionalismo, terrorismo e fronteiras', 'Empresas transnacionais e fluxos financeiros'], 2, 'H16'],
            ['HUMANAS', 'Geografia', 'Agricultura e questão agrária', 'Agronegócio, agricultura familiar, reforma agrária, conflitos no campo e Revolução Verde.', ['Estrutura fundiária e concentração de terras', 'Agronegócio x agricultura familiar', 'Revolução Verde, transgênicos e agrotóxicos', 'MST e reforma agrária', 'Trabalho análogo à escravidão'], 3, 'H17'],
            ['HUMANAS', 'Geografia', 'Indústria e energia no Brasil', 'Industrialização, desconcentração industrial, fontes de energia e infraestrutura.', ['Industrialização por substituição de importações', 'Desconcentração industrial e guerra fiscal', 'Hidrelétricas, petróleo e pré-sal', 'Energias renováveis: eólica, solar, biomassa', 'Logística e transportes'], 2, 'H17'],
            ['HUMANAS', 'Geografia', 'População e demografia', 'Transição demográfica, envelhecimento, migrações internas e internacionais, IDH.', ['Pirâmides etárias e transição demográfica', 'Migrações internas e fluxos recentes', 'Refugiados e xenofobia', 'IDH, Gini e desigualdade', 'Bônus demográfico e previdência'], 2, 'H16'],
            ['HUMANAS', 'Geografia', 'Geografia física: clima, relevo e hidrografia', 'Domínios morfoclimáticos, biomas, bacias hidrográficas e os fenômenos que aparecem nas questões.', ['Domínios morfoclimáticos de Aziz Ab’Saber', 'Biomas brasileiros e ameaças', 'Bacias hidrográficas e uso da água', 'Massas de ar, El Niño e La Niña', 'Formas de relevo e erosão'], 2, 'H18'],
            ['HUMANAS', 'Geografia', 'Cartografia', 'Escala, projeções, fusos horários, coordenadas e leitura de mapas temáticos e anamorfoses.', ['Escala numérica e gráfica', 'Projeções: Mercator, Peters, azimutal', 'Coordenadas e fusos horários', 'Curvas de nível e perfis topográficos', 'Sensoriamento remoto, GPS e SIG'], 2, 'H16'],
            ['HUMANAS', 'Filosofia', 'Filosofia antiga', 'Pré-socráticos, sofistas, Sócrates, Platão e Aristóteles — mito x razão, ética e política.', ['Passagem do mito ao logos', 'Sofistas e relativismo', 'Sócrates: maiêutica e ironia', 'Platão: mundo das ideias, alegoria da caverna', 'Aristóteles: ética das virtudes, política, lógica'], 3, 'H24'],
            ['HUMANAS', 'Filosofia', 'Filosofia moderna e contemporânea', 'Racionalismo, empirismo, contratualismo, Kant, Nietzsche, existencialismo e Escola de Frankfurt.', ['Descartes, Locke e Hume', 'Hobbes, Locke e Rousseau (contrato social)', 'Kant: ética do dever e Esclarecimento', 'Nietzsche e a crítica à moral', 'Sartre, Foucault, Adorno e Horkheimer'], 3, 'H24'],
            ['HUMANAS', 'Filosofia', 'Ética, política e direitos humanos', 'Justiça, liberdade, democracia, cidadania e a Declaração Universal dos Direitos Humanos.', ['Ética x moral', 'Justiça: Aristóteles, Rawls', 'Democracia e cidadania', 'Direitos humanos e dignidade', 'Bioética e tecnologia'], 2, 'H25'],
            ['HUMANAS', 'Sociologia', 'Clássicos da Sociologia', 'Durkheim, Weber e Marx: fato social, ação social, classes e alienação.', ['Durkheim: fato social, solidariedade, anomia', 'Weber: ação social, racionalização, burocracia', 'Marx: classes, mais-valia, alienação, ideologia', 'Comparação entre os três autores', 'Aplicações a fenômenos atuais'], 3, 'H23'],
            ['HUMANAS', 'Sociologia', 'Cidadania, movimentos sociais e desigualdade', 'Direitos civis, políticos e sociais; movimentos negro, feminista, LGBTQIA+, indígena e ambiental.', ['Marshall e as gerações de direitos', 'Movimentos sociais no Brasil', 'Desigualdade de gênero e raça', 'Estado de bem-estar social', 'Participação política e democracia'], 3, 'H25'],
            ['HUMANAS', 'Sociologia', 'Cultura, identidade e indústria cultural', 'Cultura erudita, popular e de massa; etnocentrismo, relativismo e consumo.', ['Cultura material e imaterial', 'Etnocentrismo x relativismo cultural', 'Indústria cultural (Adorno)', 'Identidade e globalização (Stuart Hall, Bauman)', 'Consumo e sociedade do espetáculo'], 2, 'H23'],
            ['HUMANAS', 'Sociologia', 'Trabalho e sociedade', 'Transformações do trabalho: fordismo, toyotismo, uberização, precarização e desemprego.', ['Divisão do trabalho e alienação', 'Fordismo, toyotismo e acumulação flexível', 'Uberização e trabalho por aplicativo', 'Reforma trabalhista e informalidade', 'Tecnologia, automação e futuro do trabalho'], 2, 'H23'],

            // ------------------------------------------------------------------ NATUREZA
            ['NATUREZA', 'Biologia', 'Ecologia', 'O tema mais recorrente de Biologia: relações ecológicas, cadeias alimentares, ciclos e impactos ambientais.', ['Níveis de organização e cadeias/teias alimentares', 'Fluxo de energia e pirâmides ecológicas', 'Ciclos biogeoquímicos (carbono, nitrogênio, água)', 'Relações ecológicas (mutualismo, predação, competição…)', 'Sucessão ecológica', 'Poluição, eutrofização, bioacumulação'], 3, 'H29'],
            ['NATUREZA', 'Biologia', 'Genética', 'Leis de Mendel, heredogramas, grupos sanguíneos, ligação ao sexo e biotecnologia.', ['1ª e 2ª leis de Mendel', 'Heredogramas e probabilidade', 'Sistema ABO e Rh', 'Herança ligada ao sexo', 'Engenharia genética, transgênicos, CRISPR e testes de DNA'], 3, 'H15'],
            ['NATUREZA', 'Biologia', 'Evolução', 'Lamarck, Darwin, seleção natural, especiação e evidências evolutivas.', ['Lamarckismo x darwinismo', 'Seleção natural e adaptação', 'Neodarwinismo e mutações', 'Especiação e isolamento', 'Evidências: fósseis, homologia, DNA', 'Resistência a antibióticos como exemplo'], 3, 'H16'],
            ['NATUREZA', 'Biologia', 'Citologia e bioquímica', 'Membrana, organelas, respiração, fotossíntese, carboidratos, lipídios, proteínas e enzimas.', ['Membrana e transportes', 'Organelas e funções', 'Respiração celular e fermentação', 'Fotossíntese', 'Enzimas e fatores que as afetam', 'Vitaminas e nutrição'], 2, 'H13'],
            ['NATUREZA', 'Biologia', 'Fisiologia humana', 'Sistemas digestório, circulatório, respiratório, excretor, nervoso, endócrino e imunológico.', ['Digestão e absorção', 'Coração, vasos e pressão', 'Trocas gasosas', 'Rins e osmorregulação', 'Hormônios e homeostase', 'Vacinas, soros e imunidade'], 3, 'H14'],
            ['NATUREZA', 'Biologia', 'Saúde pública e doenças', 'Viroses, bacterioses, protozooses e verminoses; vetores, prevenção e saneamento.', ['Dengue, zika, chikungunya e febre amarela', 'Doença de Chagas, malária, leishmaniose', 'DSTs/ISTs e prevenção', 'Saneamento básico e verminoses', 'Vacinação e epidemiologia'], 3, 'H14'],
            ['NATUREZA', 'Biologia', 'Botânica e reinos', 'Grupos vegetais, fisiologia vegetal, fungos, bactérias e classificação dos seres vivos.', ['Briófitas, pteridófitas, gimnospermas e angiospermas', 'Transporte de seiva e transpiração', 'Hormônios vegetais e fotoperiodismo', 'Fungos e bactérias: importância e doenças', 'Classificação e filogenia'], 2, 'H13'],
            ['NATUREZA', 'Física', 'Mecânica: cinemática e leis de Newton', 'Movimentos, forças, atrito, gráficos e as três leis — a base da Física no ENEM.', ['MRU, MRUV e gráficos', 'Leis de Newton e diagramas de forças', 'Atrito, plano inclinado, polias', 'Lançamentos e queda livre', 'Movimento circular e força centrípeta'], 3, 'H20'],
            ['NATUREZA', 'Física', 'Energia, trabalho e potência', 'Conservação de energia, trabalho, potência, rendimento e quantidade de movimento.', ['Trabalho e potência', 'Energia cinética e potencial', 'Conservação de energia mecânica', 'Impulso e quantidade de movimento; colisões', 'Rendimento de máquinas e consumo'], 3, 'H23'],
            ['NATUREZA', 'Física', 'Eletricidade', 'Circuitos, lei de Ohm, potência elétrica, consumo (kWh) e segurança — muito cobrado no cotidiano.', ['Corrente, tensão e resistência', 'Associação de resistores', 'Potência e consumo em kWh', 'Chuveiros, lâmpadas e disjuntores', 'Geradores, receptores e eletrostática básica'], 3, 'H21'],
            ['NATUREZA', 'Física', 'Ondas, som e luz', 'Ondulatória, acústica e óptica: frequência, ressonância, efeito Doppler, espelhos, lentes e cores.', ['Características das ondas e fenômenos', 'Som: intensidade, altura, timbre, ressonância', 'Efeito Doppler', 'Espelhos e lentes; olho humano e defeitos de visão', 'Espectro eletromagnético e cores'], 3, 'H22'],
            ['NATUREZA', 'Física', 'Termologia', 'Calor, temperatura, dilatação, trocas de calor, mudanças de fase e termodinâmica.', ['Escalas termométricas', 'Calor sensível e latente', 'Condução, convecção e irradiação', 'Dilatação', 'Gases e leis da termodinâmica; máquinas térmicas'], 2, 'H21'],
            ['NATUREZA', 'Física', 'Eletromagnetismo e Física moderna', 'Campos magnéticos, indução, transformadores, motores e noções de física moderna.', ['Ímãs e campo magnético', 'Força magnética e motores', 'Indução eletromagnética e transformadores', 'Geração e transmissão de energia', 'Efeito fotoelétrico, radioatividade e relatividade (noções)'], 2, 'H21'],
            ['NATUREZA', 'Física', 'Hidrostática', 'Pressão, empuxo, densidade e o princípio de Pascal em situações do cotidiano.', ['Pressão e pressão atmosférica', 'Teorema de Stevin', 'Princípio de Pascal e prensa hidráulica', 'Empuxo e flutuação', 'Densidade e vasos comunicantes'], 2, 'H20'],
            ['NATUREZA', 'Química', 'Estequiometria', 'Cálculos com mol, massa, volume, rendimento, pureza e reagente limitante.', ['Mol, massa molar e volume molar', 'Balanceamento de equações', 'Proporções estequiométricas', 'Rendimento e pureza', 'Reagente limitante e em excesso'], 3, 'H24'],
            ['NATUREZA', 'Química', 'Química orgânica', 'Funções orgânicas, isomeria, reações e polímeros — sempre ligados a combustíveis, fármacos e plásticos.', ['Funções: hidrocarbonetos, álcool, ácido, éster, amina, amida', 'Isomeria plana e espacial', 'Reações: combustão, esterificação, saponificação', 'Polímeros e plásticos', 'Biodiesel e biocombustíveis'], 3, 'H24'],
            ['NATUREZA', 'Química', 'Soluções e propriedades coligativas', 'Concentração, diluição, mistura de soluções e efeitos coligativos.', ['Concentração comum, mol/L, ppm e título', 'Diluição e mistura', 'Solubilidade e curvas', 'Propriedades coligativas', 'Osmose e osmose reversa'], 2, 'H24'],
            ['NATUREZA', 'Química', 'Eletroquímica e reações redox', 'Pilhas, eletrólise, oxidação/redução, corrosão e baterias.', ['Número de oxidação e balanceamento redox', 'Pilhas: potencial e ddp', 'Eletrólise e galvanoplastia', 'Corrosão e proteção', 'Baterias de lítio e reciclagem'], 2, 'H25'],
            ['NATUREZA', 'Química', 'Termoquímica e cinética', 'Entalpia, reações endo/exotérmicas, energia de combustíveis, velocidade de reações e catalisadores.', ['Entalpia e diagramas de energia', 'Lei de Hess', 'Poder calorífico de combustíveis', 'Fatores que alteram a velocidade', 'Catalisadores e enzimas'], 2, 'H24'],
            ['NATUREZA', 'Química', 'Equilíbrio químico e pH', 'Constante de equilíbrio, deslocamento (Le Chatelier), ácidos, bases, pH e tampões.', ['Kc, Kp e deslocamento', 'Le Chatelier', 'Ácidos e bases, força e ionização', 'pH, pOH e indicadores', 'Solução-tampão e sangue; chuva ácida'], 2, 'H25'],
            ['NATUREZA', 'Química', 'Química ambiental', 'Poluição do ar, da água e do solo; tratamento de água e esgoto; camada de ozônio; lixo.', ['Efeito estufa, CFCs e ozônio', 'Chuva ácida e inversão térmica', 'Tratamento de água (floculação, cloração)', 'Metais pesados e contaminação', 'Reciclagem e resíduos'], 3, 'H26'],
            ['NATUREZA', 'Química', 'Tabela periódica, ligações e forças intermoleculares', 'Propriedades periódicas, ligações iônica/covalente/metálica e forças que explicam pontos de ebulição e solubilidade.', ['Propriedades periódicas', 'Ligações químicas e geometria', 'Polaridade', 'Forças intermoleculares', 'Solubilidade e ponto de ebulição'], 2, 'H24'],
            ['NATUREZA', 'Química', 'Separação de misturas e radioatividade', 'Métodos de separação e noções de radioatividade e suas aplicações.', ['Filtração, decantação, destilação, cromatografia', 'Substâncias puras x misturas', 'Emissões alfa, beta e gama', 'Meia-vida e datação', 'Usos médicos e acidentes nucleares'], 2, 'H26'],

            // ------------------------------------------------------------------ MATEMÁTICA
            ['MATEMATICA', 'Matemática', 'Razão, proporção e porcentagem', 'O tema número 1 da prova: regra de três, porcentagem, aumentos sucessivos, escalas e juros.', ['Razão e proporção; grandezas direta e inversamente proporcionais', 'Regra de três simples e composta', 'Porcentagem, aumentos e descontos sucessivos', 'Juros simples e compostos', 'Escala e densidade demográfica'], 3, 'H3'],
            ['MATEMATICA', 'Matemática', 'Funções', 'Função afim, quadrática, exponencial e logarítmica em gráficos e situações reais.', ['Função afim: taxa de variação, gráfico, zero', 'Função quadrática: vértice, máximo e mínimo', 'Exponencial: crescimento e decaimento', 'Logaritmo: escala Richter, pH, decibéis', 'Interpretação de gráficos de funções'], 3, 'H20'],
            ['MATEMATICA', 'Matemática', 'Estatística', 'Média, mediana, moda, desvio padrão e leitura crítica de gráficos e tabelas.', ['Média, mediana e moda', 'Média ponderada', 'Variância e desvio padrão', 'Gráficos: barras, setores, linhas, histogramas', 'Amostra, população e interpretação'], 3, 'H27'],
            ['MATEMATICA', 'Matemática', 'Probabilidade', 'Espaço amostral, eventos, probabilidade condicional e independência em problemas contextualizados.', ['Espaço amostral e evento', 'Probabilidade de união e interseção', 'Probabilidade condicional', 'Eventos independentes', 'Probabilidade com contagem'], 3, 'H28'],
            ['MATEMATICA', 'Matemática', 'Análise combinatória', 'Princípio fundamental da contagem, permutações, arranjos e combinações.', ['Princípio multiplicativo', 'Permutação simples e com repetição', 'Arranjo x combinação', 'Problemas de senhas, placas e comissões', 'Combinatória com restrições'], 2, 'H2'],
            ['MATEMATICA', 'Matemática', 'Geometria plana', 'Áreas, perímetros, semelhança de triângulos, Pitágoras, círculo e polígonos.', ['Áreas de figuras planas e compostas', 'Perímetro e cercamento', 'Semelhança e escala', 'Teorema de Pitágoras', 'Ângulos, polígonos regulares e círculo'], 3, 'H7'],
            ['MATEMATICA', 'Matemática', 'Geometria espacial', 'Volumes e áreas de prismas, cilindros, pirâmides, cones e esferas; planificações.', ['Volume de prisma e cilindro', 'Pirâmide e cone', 'Esfera', 'Planificações e vistas', 'Conversão de unidades de volume (m³, L, mL)'], 3, 'H8'],
            ['MATEMATICA', 'Matemática', 'Trigonometria', 'Razões trigonométricas no triângulo retângulo, lei dos senos e cossenos e funções periódicas.', ['Seno, cosseno e tangente', 'Ângulos notáveis', 'Lei dos senos e dos cossenos', 'Ciclo trigonométrico', 'Funções periódicas (marés, ondas)'], 2, 'H9'],
            ['MATEMATICA', 'Matemática', 'Progressões e sequências', 'PA, PG, padrões numéricos e aplicações financeiras.', ['Termo geral e soma da PA', 'Termo geral e soma da PG', 'Padrões e sequências figurativas', 'PG e juros compostos', 'Sequências recursivas'], 2, 'H4'],
            ['MATEMATICA', 'Matemática', 'Aritmética e números', 'Operações, frações, múltiplos, divisores, MMC/MDC, notação científica e unidades de medida.', ['Frações, decimais e operações', 'MMC e MDC em problemas', 'Notação científica e ordens de grandeza', 'Conversão de unidades (tempo, comprimento, massa)', 'Sistemas de numeração e divisibilidade'], 3, 'H1'],
            ['MATEMATICA', 'Matemática', 'Matemática financeira', 'Juros, descontos, parcelamentos, inflação e comparação de propostas.', ['Juros simples e compostos', 'Montante e prestações', 'Desconto à vista x parcelado', 'Inflação e reajustes', 'Comparação de investimentos'], 2, 'H3'],
            ['MATEMATICA', 'Matemática', 'Geometria analítica', 'Plano cartesiano, distância, ponto médio, equação da reta e da circunferência.', ['Distância entre pontos e ponto médio', 'Coeficiente angular e equação da reta', 'Retas paralelas e perpendiculares', 'Circunferência', 'Localização e mapas em coordenadas'], 2, 'H6'],
            ['MATEMATICA', 'Matemática', 'Equações, sistemas e inequações', 'Equações de 1º e 2º graus, sistemas lineares e inequações em problemas do cotidiano.', ['Equações de 1º grau e modelagem', 'Equação de 2º grau: Bhaskara e soma/produto', 'Sistemas lineares', 'Inequações', 'Problemas com duas variáveis'], 2, 'H21'],
            ['MATEMATICA', 'Matemática', 'Leitura de gráficos e tabelas', 'Interpretar, comparar e tirar conclusões de gráficos e tabelas — a habilidade mais cobrada de todas.', ['Gráficos de linha, barras e setores', 'Tabelas de dupla entrada', 'Taxa de variação e tendência', 'Gráficos enganosos e escala', 'Cruzar informações de dois gráficos'], 3, 'H24'],
            ['MATEMATICA', 'Matemática', 'Raciocínio lógico e matrizes', 'Lógica, tabelas-verdade, princípio da casa dos pombos e matrizes/determinantes em contextos.', ['Proposições e conectivos', 'Negação de "todo" e "algum"', 'Problemas de lógica', 'Matrizes: operações e aplicações', 'Determinantes básicos'], 1, 'H2'],
        ];
    }

    public function run(): void
    {
        foreach (self::topics() as $t) {
            [$area, $discipline, $name, $description, $subtopics, $recurrence] = $t;
            StudyTopic::updateOrCreate(['slug' => Str::slug($name)], [
                'area' => $area, 'discipline' => $discipline, 'name' => $name, 'description' => $description,
                'subtopics' => $subtopics, 'recurrence' => $recurrence, 'matrix_skill' => $t[6] ?? null,
                'source_type' => 'EDITORIAL', 'review_status' => 'VERIFIED',
            ]);
        }
    }
}
